[build]
  command = "npm start && sleep 5s && gssg --domain 'http://localhost:2368' --url 'https://www.letssewbelfast.com' --dest static"
  publish = "static/"

[template]
  incoming-hooks = ["Ghost"]
